#!/usr/bin/env bash
# while and if statement together
i=1
while [ $i -le 10 ]; do
    if [ $i -eq 9 ]; then
        echo -e "Hi\nBest School"
    else
        echo "Best School"
    fi
    ((i++))
done