#!/usr/bin/env bash
# if statements and loops
i=1
while [ $i -le 20 ]; do
    case $i in
        4)
            echo "bad luck from China"
            ((i++))
            ;;
        9)
            echo "bad luck from Japan"
            ((i++))
            ;;
        17)
            echo "bad luck from Italy"
            ((i++))
            ;;
        *)
            echo $i
            ((i++))
            ;;
    esac
done