#!/usr/bin/env bash
# clock
minutes=1
hours=0
while [ $hours -le 12]; do
    echo "Hour: $hours"
    while [ $minutes -le 59 ]; do
        echo $minutes
        ((minutes++))
    done
    ((hours++))
done
